// GENERATED by backend/scripts/impact_study.py — do not edit by hand.
export const IMPACT_DATA = {
 "generated": "2026-07-12",
 "types": {
  "household_leverage": {
   "label": "Household / credit-leverage bust",
   "episodes": [
    {
     "onset": "1990-08",
     "equity_dd": -14.6,
     "equity_tt_mo": 2,
     "equity_rec_mo": 6,
     "housing_nom_dd": -0.4,
     "housing_nom_tt_mo": 2,
     "housing_nom_rec_mo": 5,
     "housing_real_dd": -5.0,
     "housing_real_tt_mo": 53,
     "tsy_12m": 21.4,
     "tsy_24m": 56.6,
     "unemp_rise_pp": 2.1
    },
    {
     "onset": "2008-01",
     "equity_dd": -53.3,
     "equity_tt_mo": 14,
     "equity_rec_mo": 72,
     "housing_nom_dd": -17.7,
     "housing_nom_tt_mo": 51,
     "housing_nom_rec_mo": 102,
     "housing_real_dd": -24.9,
     "housing_real_tt_mo": 51,
     "tsy_12m": 26.7,
     "tsy_24m": 6.3,
     "unemp_rise_pp": 5.0
    }
   ],
   "paths": {
    "eq_path": [
     {
      "m": -12,
      "v": 102.9
     },
     {
      "m": -11,
      "v": 104.2
     },
     {
      "m": -10,
      "v": 102.8
     },
     {
      "m": -9,
      "v": 104.0
     },
     {
      "m": -8,
      "v": 106.7
     },
     {
      "m": -7,
      "v": 105.6
     },
     {
      "m": -6,
      "v": 104.8
     },
     {
      "m": -5,
      "v": 102.8
     },
     {
      "m": -4,
      "v": 104.4
     },
     {
      "m": -3,
      "v": 108.1
     },
     {
      "m": -2,
      "v": 107.2
     },
     {
      "m": -1,
      "v": 107.7
     },
     {
      "m": 0,
      "v": 100.0
     },
     {
      "m": 1,
      "v": 97.0
     },
     {
      "m": 2,
      "v": 94.1
     },
     {
      "m": 3,
      "v": 97.5
     },
     {
      "m": 4,
      "v": 100.8
     },
     {
      "m": 5,
      "v": 98.1
     },
     {
      "m": 6,
      "v": 100.5
     },
     {
      "m": 7,
      "v": 101.7
     },
     {
      "m": 8,
      "v": 100.3
     },
     {
      "m": 9,
      "v": 90.4
     },
     {
      "m": 10,
      "v": 87.3
     },
     {
      "m": 11,
      "v": 87.5
     },
     {
      "m": 12,
      "v": 88.7
     },
     {
      "m": 13,
      "v": 86.1
     },
     {
      "m": 14,
      "v": 84.6
     },
     {
      "m": 15,
      "v": 87.8
     },
     {
      "m": 16,
      "v": 90.8
     },
     {
      "m": 17,
      "v": 95.8
     },
     {
      "m": 18,
      "v": 95.7
     },
     {
      "m": 19,
      "v": 97.9
     },
     {
      "m": 20,
      "v": 99.2
     },
     {
      "m": 21,
      "v": 101.1
     },
     {
      "m": 22,
      "v": 100.5
     },
     {
      "m": 23,
      "v": 102.0
     },
     {
      "m": 24,
      "v": 102.9
     },
     {
      "m": 25,
      "v": 101.3
     },
     {
      "m": 26,
      "v": 102.6
     },
     {
      "m": 27,
      "v": 105.6
     },
     {
      "m": 28,
      "v": 104.2
     },
     {
      "m": 29,
      "v": 102.9
     },
     {
      "m": 30,
      "v": 104.1
     },
     {
      "m": 31,
      "v": 106.1
     },
     {
      "m": 32,
      "v": 106.4
     },
     {
      "m": 33,
      "v": 108.6
     },
     {
      "m": 34,
      "v": 109.5
     },
     {
      "m": 35,
      "v": 111.0
     },
     {
      "m": 36,
      "v": 113.6
     },
     {
      "m": 37,
      "v": 115.8
     },
     {
      "m": 38,
      "v": 116.1
     },
     {
      "m": 39,
      "v": 116.7
     },
     {
      "m": 40,
      "v": 116.8
     },
     {
      "m": 41,
      "v": 116.5
     },
     {
      "m": 42,
      "v": 117.4
     },
     {
      "m": 43,
      "v": 110.9
     },
     {
      "m": 44,
      "v": 107.1
     },
     {
      "m": 45,
      "v": 108.3
     },
     {
      "m": 46,
      "v": 109.2
     },
     {
      "m": 47,
      "v": 109.1
     },
     {
      "m": 48,
      "v": 112.7
     }
    ],
    "hpi_path": [
     {
      "m": -12,
      "v": 102.3
     },
     {
      "m": -9,
      "v": 102.2
     },
     {
      "m": -6,
      "v": 101.1
     },
     {
      "m": -3,
      "v": 100.7
     },
     {
      "m": 0,
      "v": 100.0
     },
     {
      "m": 3,
      "v": 97.5
     },
     {
      "m": 6,
      "v": 94.4
     },
     {
      "m": 9,
      "v": 93.5
     },
     {
      "m": 12,
      "v": 94.2
     },
     {
      "m": 15,
      "v": 91.8
     },
     {
      "m": 18,
      "v": 89.4
     },
     {
      "m": 21,
      "v": 88.7
     },
     {
      "m": 24,
      "v": 87.6
     },
     {
      "m": 27,
      "v": 86.8
     },
     {
      "m": 30,
      "v": 87.7
     },
     {
      "m": 33,
      "v": 87.0
     },
     {
      "m": 36,
      "v": 84.6
     },
     {
      "m": 39,
      "v": 83.1
     },
     {
      "m": 42,
      "v": 83.7
     },
     {
      "m": 45,
      "v": 84.1
     },
     {
      "m": 48,
      "v": 83.3
     },
     {
      "m": 51,
      "v": 82.9
     },
     {
      "m": 54,
      "v": 84.0
     },
     {
      "m": 57,
      "v": 84.6
     },
     {
      "m": 60,
      "v": 85.1
     }
    ]
   },
   "aggregate": {
    "equity_dd": {
     "median": -33.9,
     "values": [
      -14.6,
      -53.3
     ]
    },
    "equity_tt_mo": {
     "median": 8.0,
     "values": [
      2,
      14
     ]
    },
    "equity_rec_mo": {
     "median": 39.0,
     "values": [
      6,
      72
     ]
    },
    "housing_nom_dd": {
     "median": -9.0,
     "values": [
      -0.4,
      -17.7
     ]
    },
    "housing_nom_tt_mo": {
     "median": 26.5,
     "values": [
      2,
      51
     ]
    },
    "housing_real_dd": {
     "median": -14.9,
     "values": [
      -5.0,
      -24.9
     ]
    },
    "tsy_12m": {
     "median": 24.0,
     "values": [
      21.4,
      26.7
     ]
    },
    "tsy_24m": {
     "median": 31.4,
     "values": [
      56.6,
      6.3
     ]
    },
    "unemp_rise_pp": {
     "median": 3.5,
     "values": [
      2.1,
      5.0
     ]
    }
   }
  },
  "valuation_corporate": {
   "label": "Valuation / corporate unwind",
   "episodes": [
    {
     "onset": "2001-04",
     "equity_dd": -33.1,
     "equity_tt_mo": 23,
     "equity_rec_mo": 44,
     "housing_nom_dd": 0.0,
     "housing_nom_tt_mo": 0,
     "housing_nom_rec_mo": 0,
     "housing_real_dd": 0.0,
     "housing_real_tt_mo": 0,
     "tsy_12m": 3.8,
     "tsy_24m": 31.8,
     "unemp_rise_pp": 1.9
    }
   ],
   "paths": {
    "eq_path": [
     {
      "m": -12,
      "v": 106.5
     },
     {
      "m": -11,
      "v": 105.4
     },
     {
      "m": -10,
      "v": 107.1
     },
     {
      "m": -9,
      "v": 107.6
     },
     {
      "m": -8,
      "v": 109.8
     },
     {
      "m": -7,
      "v": 110.0
     },
     {
      "m": -6,
      "v": 106.5
     },
     {
      "m": -5,
      "v": 106.4
     },
     {
      "m": -4,
      "v": 106.3
     },
     {
      "m": -3,
      "v": 107.2
     },
     {
      "m": -2,
      "v": 106.8
     },
     {
      "m": -1,
      "v": 99.4
     },
     {
      "m": 0,
      "v": 100.0
     },
     {
      "m": 1,
      "v": 106.2
     },
     {
      "m": 2,
      "v": 104.0
     },
     {
      "m": 3,
      "v": 101.2
     },
     {
      "m": 4,
      "v": 99.6
     },
     {
      "m": 5,
      "v": 90.9
     },
     {
      "m": 6,
      "v": 91.6
     },
     {
      "m": 7,
      "v": 94.8
     },
     {
      "m": 8,
      "v": 96.1
     },
     {
      "m": 9,
      "v": 95.9
     },
     {
      "m": 10,
      "v": 93.9
     },
     {
      "m": 11,
      "v": 99.0
     },
     {
      "m": 12,
      "v": 96.8
     },
     {
      "m": 13,
      "v": 94.9
     },
     {
      "m": 14,
      "v": 89.7
     },
     {
      "m": 15,
      "v": 80.3
     },
     {
      "m": 16,
      "v": 81.1
     },
     {
      "m": 17,
      "v": 77.8
     },
     {
      "m": 18,
      "v": 75.8
     },
     {
      "m": 19,
      "v": 79.7
     },
     {
      "m": 20,
      "v": 79.1
     },
     {
      "m": 21,
      "v": 78.8
     },
     {
      "m": 22,
      "v": 73.8
     },
     {
      "m": 23,
      "v": 73.6
     },
     {
      "m": 24,
      "v": 77.6
     },
     {
      "m": 25,
      "v": 82.1
     },
     {
      "m": 26,
      "v": 87.0
     },
     {
      "m": 27,
      "v": 86.8
     },
     {
      "m": 28,
      "v": 87.0
     },
     {
      "m": 29,
      "v": 89.5
     },
     {
      "m": 30,
      "v": 91.9
     },
     {
      "m": 31,
      "v": 93.4
     },
     {
      "m": 32,
      "v": 97.4
     },
     {
      "m": 33,
      "v": 102.3
     },
     {
      "m": 34,
      "v": 103.8
     },
     {
      "m": 35,
      "v": 102.5
     },
     {
      "m": 36,
      "v": 102.9
     },
     {
      "m": 37,
      "v": 99.4
     },
     {
      "m": 38,
      "v": 102.1
     },
     {
      "m": 39,
      "v": 100.5
     },
     {
      "m": 40,
      "v": 99.0
     },
     {
      "m": 41,
      "v": 102.1
     },
     {
      "m": 42,
      "v": 103.0
     },
     {
      "m": 43,
      "v": 108.1
     },
     {
      "m": 44,
      "v": 111.2
     },
     {
      "m": 45,
      "v": 110.0
     },
     {
      "m": 46,
      "v": 112.9
     },
     {
      "m": 47,
      "v": 113.3
     },
     {
      "m": 48,
      "v": 110.3
     }
    ],
    "hpi_path": [
     {
      "m": -12,
      "v": 92.8
     },
     {
      "m": -9,
      "v": 94.5
     },
     {
      "m": -6,
      "v": 96.0
     },
     {
      "m": -3,
      "v": 98.4
     },
     {
      "m": 0,
      "v": 100.0
     },
     {
      "m": 3,
      "v": 101.5
     },
     {
      "m": 6,
      "v": 102.8
     },
     {
      "m": 9,
      "v": 104.3
     },
     {
      "m": 12,
      "v": 106.1
     },
     {
      "m": 15,
      "v": 108.2
     },
     {
      "m": 18,
      "v": 109.7
     },
     {
      "m": 21,
      "v": 111.0
     },
     {
      "m": 24,
      "v": 112.4
     },
     {
      "m": 27,
      "v": 114.1
     },
     {
      "m": 30,
      "v": 117.3
     },
     {
      "m": 33,
      "v": 119.2
     },
     {
      "m": 36,
      "v": 122.1
     },
     {
      "m": 39,
      "v": 126.8
     },
     {
      "m": 42,
      "v": 129.5
     },
     {
      "m": 45,
      "v": 132.4
     },
     {
      "m": 48,
      "v": 136.7
     },
     {
      "m": 51,
      "v": 140.8
     },
     {
      "m": 54,
      "v": 144.0
     },
     {
      "m": 57,
      "v": 146.3
     },
     {
      "m": 60,
      "v": 147.8
     }
    ]
   },
   "aggregate": {
    "equity_dd": {
     "median": -33.1,
     "values": [
      -33.1
     ]
    },
    "equity_tt_mo": {
     "median": 23,
     "values": [
      23
     ]
    },
    "equity_rec_mo": {
     "median": 44,
     "values": [
      44
     ]
    },
    "housing_nom_dd": {
     "median": 0.0,
     "values": [
      0.0
     ]
    },
    "housing_nom_tt_mo": {
     "median": 0,
     "values": [
      0
     ]
    },
    "housing_real_dd": {
     "median": 0.0,
     "values": [
      0.0
     ]
    },
    "tsy_12m": {
     "median": 3.8,
     "values": [
      3.8
     ]
    },
    "tsy_24m": {
     "median": 31.8,
     "values": [
      31.8
     ]
    },
    "unemp_rise_pp": {
     "median": 1.9,
     "values": [
      1.9
     ]
    }
   }
  },
  "inflation_rates": {
   "label": "Inflation / rates-driven",
   "episodes": [
    {
     "onset": "1957-09",
     "equity_dd": -15.0,
     "equity_tt_mo": 2,
     "equity_rec_mo": 12,
     "housing_nom_dd": null,
     "housing_nom_tt_mo": null,
     "housing_nom_rec_mo": null,
     "housing_real_dd": null,
     "housing_real_tt_mo": null,
     "tsy_12m": 5.8,
     "tsy_24m": -5.0,
     "unemp_rise_pp": 3.1
    },
    {
     "onset": "1960-05",
     "equity_dd": -14.7,
     "equity_tt_mo": 25,
     "equity_rec_mo": 32,
     "housing_nom_dd": null,
     "housing_nom_tt_mo": null,
     "housing_nom_rec_mo": null,
     "housing_real_dd": null,
     "housing_real_tt_mo": null,
     "tsy_12m": 15.3,
     "tsy_24m": 16.8,
     "unemp_rise_pp": 2.0
    },
    {
     "onset": "1970-01",
     "equity_dd": -29.7,
     "equity_tt_mo": 6,
     "equity_rec_mo": 26,
     "housing_nom_dd": null,
     "housing_nom_tt_mo": null,
     "housing_nom_rec_mo": null,
     "housing_real_dd": null,
     "housing_real_tt_mo": null,
     "tsy_12m": 33.4,
     "tsy_24m": 47.6,
     "unemp_rise_pp": 2.2
    },
    {
     "onset": "1973-12",
     "equity_dd": -45.0,
     "equity_tt_mo": 12,
     "equity_rec_mo": 74,
     "housing_nom_dd": null,
     "housing_nom_tt_mo": null,
     "housing_nom_rec_mo": null,
     "housing_real_dd": null,
     "housing_real_tt_mo": null,
     "tsy_12m": -2.4,
     "tsy_24m": -2.4,
     "unemp_rise_pp": 4.1
    },
    {
     "onset": "1980-02",
     "equity_dd": -11.5,
     "equity_tt_mo": 2,
     "equity_rec_mo": 5,
     "housing_nom_dd": 1.7,
     "housing_nom_tt_mo": 2,
     "housing_nom_rec_mo": 2,
     "housing_real_dd": -16.1,
     "housing_real_tt_mo": 29,
     "tsy_12m": 1.5,
     "tsy_24m": 1.2,
     "unemp_rise_pp": 4.5
    },
    {
     "onset": "1981-08",
     "equity_dd": -19.6,
     "equity_tt_mo": 11,
     "equity_rec_mo": 15,
     "housing_nom_dd": -2.5,
     "housing_nom_tt_mo": 5,
     "housing_nom_rec_mo": 14,
     "housing_real_dd": -9.0,
     "housing_real_tt_mo": 11,
     "tsy_12m": 38.6,
     "tsy_24m": 75.4,
     "unemp_rise_pp": 3.4
    }
   ],
   "paths": {
    "eq_path": [
     {
      "m": -12,
      "v": 102.6
     },
     {
      "m": -11,
      "v": 102.6
     },
     {
      "m": -10,
      "v": 107.7
     },
     {
      "m": -9,
      "v": 107.3
     },
     {
      "m": -8,
      "v": 103.2
     },
     {
      "m": -7,
      "v": 102.5
     },
     {
      "m": -6,
      "v": 102.0
     },
     {
      "m": -5,
      "v": 103.0
     },
     {
      "m": -4,
      "v": 105.1
     },
     {
      "m": -3,
      "v": 103.5
     },
     {
      "m": -2,
      "v": 104.3
     },
     {
      "m": -1,
      "v": 100.8
     },
     {
      "m": 0,
      "v": 100.0
     },
     {
      "m": 1,
      "v": 95.3
     },
     {
      "m": 2,
      "v": 95.3
     },
     {
      "m": 3,
      "v": 94.5
     },
     {
      "m": 4,
      "v": 96.3
     },
     {
      "m": 5,
      "v": 94.2
     },
     {
      "m": 6,
      "v": 94.5
     },
     {
      "m": 7,
      "v": 90.3
     },
     {
      "m": 8,
      "v": 93.5
     },
     {
      "m": 9,
      "v": 95.7
     },
     {
      "m": 10,
      "v": 97.2
     },
     {
      "m": 11,
      "v": 102.3
     },
     {
      "m": 12,
      "v": 106.1
     },
     {
      "m": 13,
      "v": 109.1
     },
     {
      "m": 14,
      "v": 110.5
     },
     {
      "m": 15,
      "v": 114.0
     },
     {
      "m": 16,
      "v": 113.2
     },
     {
      "m": 17,
      "v": 112.0
     },
     {
      "m": 18,
      "v": 113.2
     },
     {
      "m": 19,
      "v": 111.3
     },
     {
      "m": 20,
      "v": 111.8
     },
     {
      "m": 21,
      "v": 112.0
     },
     {
      "m": 22,
      "v": 112.4
     },
     {
      "m": 23,
      "v": 110.3
     },
     {
      "m": 24,
      "v": 109.0
     },
     {
      "m": 25,
      "v": 108.8
     },
     {
      "m": 26,
      "v": 112.7
     },
     {
      "m": 27,
      "v": 113.7
     },
     {
      "m": 28,
      "v": 113.1
     },
     {
      "m": 29,
      "v": 112.7
     },
     {
      "m": 30,
      "v": 112.4
     },
     {
      "m": 31,
      "v": 115.5
     },
     {
      "m": 32,
      "v": 117.1
     },
     {
      "m": 33,
      "v": 119.2
     },
     {
      "m": 34,
      "v": 119.4
     },
     {
      "m": 35,
      "v": 120.9
     },
     {
      "m": 36,
      "v": 126.0
     },
     {
      "m": 37,
      "v": 122.8
     },
     {
      "m": 38,
      "v": 122.8
     },
     {
      "m": 39,
      "v": 121.8
     },
     {
      "m": 40,
      "v": 123.0
     },
     {
      "m": 41,
      "v": 126.6
     },
     {
      "m": 42,
      "v": 130.0
     },
     {
      "m": 43,
      "v": 130.8
     },
     {
      "m": 44,
      "v": 132.8
     },
     {
      "m": 45,
      "v": 135.6
     },
     {
      "m": 46,
      "v": 137.9
     },
     {
      "m": 47,
      "v": 139.6
     },
     {
      "m": 48,
      "v": 135.6
     }
    ],
    "hpi_path": []
   },
   "aggregate": {
    "equity_dd": {
     "median": -17.3,
     "values": [
      -15.0,
      -14.7,
      -29.7,
      -45.0,
      -11.5,
      -19.6
     ]
    },
    "equity_tt_mo": {
     "median": 8.5,
     "values": [
      2,
      25,
      6,
      12,
      2,
      11
     ]
    },
    "equity_rec_mo": {
     "median": 20.5,
     "values": [
      12,
      32,
      26,
      74,
      5,
      15
     ]
    },
    "housing_nom_dd": {
     "median": -0.4,
     "values": [
      null,
      null,
      null,
      null,
      1.7,
      -2.5
     ]
    },
    "housing_nom_tt_mo": {
     "median": 3.5,
     "values": [
      null,
      null,
      null,
      null,
      2,
      5
     ]
    },
    "housing_real_dd": {
     "median": -12.6,
     "values": [
      null,
      null,
      null,
      null,
      -16.1,
      -9.0
     ]
    },
    "tsy_12m": {
     "median": 10.6,
     "values": [
      5.8,
      15.3,
      33.4,
      -2.4,
      1.5,
      38.6
     ]
    },
    "tsy_24m": {
     "median": 9.0,
     "values": [
      -5.0,
      16.8,
      47.6,
      -2.4,
      1.2,
      75.4
     ]
    },
    "unemp_rise_pp": {
     "median": 3.2,
     "values": [
      3.1,
      2.0,
      2.2,
      4.1,
      4.5,
      3.4
     ]
    }
   }
  },
  "exogenous": {
   "label": "Exogenous shock",
   "episodes": [
    {
     "onset": "2020-03",
     "equity_dd": -23.3,
     "equity_tt_mo": 0,
     "equity_rec_mo": 9,
     "housing_nom_dd": 1.0,
     "housing_nom_tt_mo": 1,
     "housing_nom_rec_mo": 1,
     "housing_real_dd": 2.2,
     "housing_real_tt_mo": 1,
     "tsy_12m": -12.3,
     "tsy_24m": -19.1,
     "unemp_rise_pp": 10.4
    }
   ],
   "paths": {
    "eq_path": [
     {
      "m": -12,
      "v": 117.7
     },
     {
      "m": -11,
      "v": 120.5
     },
     {
      "m": -10,
      "v": 118.1
     },
     {
      "m": -9,
      "v": 119.6
     },
     {
      "m": -8,
      "v": 122.9
     },
     {
      "m": -7,
      "v": 117.7
     },
     {
      "m": -6,
      "v": 121.2
     },
     {
      "m": -5,
      "v": 120.8
     },
     {
      "m": -4,
      "v": 125.3
     },
     {
      "m": -3,
      "v": 127.9
     },
     {
      "m": -2,
      "v": 130.3
     },
     {
      "m": -1,
      "v": 128.1
     },
     {
      "m": 0,
      "v": 100.0
     },
     {
      "m": 1,
      "v": 101.3
     },
     {
      "m": 2,
      "v": 105.2
     },
     {
      "m": 3,
      "v": 112.7
     },
     {
      "m": 4,
      "v": 114.6
     },
     {
      "m": 5,
      "v": 120.1
     },
     {
      "m": 6,
      "v": 119.2
     },
     {
      "m": 7,
      "v": 120.9
     },
     {
      "m": 8,
      "v": 127.7
     },
     {
      "m": 9,
      "v": 134.0
     },
     {
      "m": 10,
      "v": 138.2
     },
     {
      "m": 11,
      "v": 141.7
     },
     {
      "m": 12,
      "v": 144.3
     },
     {
      "m": 13,
      "v": 149.6
     },
     {
      "m": 14,
      "v": 152.8
     },
     {
      "m": 15,
      "v": 154.5
     },
     {
      "m": 16,
      "v": 154.1
     },
     {
      "m": 17,
      "v": 155.9
     },
     {
      "m": 18,
      "v": 154.4
     },
     {
      "m": 19,
      "v": 156.1
     },
     {
      "m": 20,
      "v": 159.2
     },
     {
      "m": 21,
      "v": 156.6
     },
     {
      "m": 22,
      "v": 157.4
     },
     {
      "m": 23,
      "v": 154.6
     },
     {
      "m": 24,
      "v": 152.3
     },
     {
      "m": 25,
      "v": 152.9
     },
     {
      "m": 26,
      "v": 143.8
     },
     {
      "m": 27,
      "v": 139.1
     },
     {
      "m": 28,
      "v": 136.9
     },
     {
      "m": 29,
      "v": 143.6
     },
     {
      "m": 30,
      "v": 134.5
     },
     {
      "m": 31,
      "v": 131.4
     },
     {
      "m": 32,
      "v": 141.4
     },
     {
      "m": 33,
      "v": 142.5
     },
     {
      "m": 34,
      "v": 146.3
     },
     {
      "m": 35,
      "v": 147.6
     },
     {
      "m": 36,
      "v": 140.5
     },
     {
      "m": 37,
      "v": 144.5
     },
     {
      "m": 38,
      "v": 141.8
     },
     {
      "m": 39,
      "v": 145.2
     },
     {
      "m": 40,
      "v": 150.1
     },
     {
      "m": 41,
      "v": 149.0
     },
     {
      "m": 42,
      "v": 147.3
     },
     {
      "m": 43,
      "v": 141.2
     },
     {
      "m": 44,
      "v": 146.0
     },
     {
      "m": 45,
      "v": 154.2
     },
     {
      "m": 46,
      "v": 156.7
     },
     {
      "m": 47,
      "v": 161.7
     },
     {
      "m": 48,
      "v": 167.7
     }
    ],
    "hpi_path": []
   },
   "aggregate": {
    "equity_dd": {
     "median": -23.3,
     "values": [
      -23.3
     ]
    },
    "equity_tt_mo": {
     "median": 0,
     "values": [
      0
     ]
    },
    "equity_rec_mo": {
     "median": 9,
     "values": [
      9
     ]
    },
    "housing_nom_dd": {
     "median": 1.0,
     "values": [
      1.0
     ]
    },
    "housing_nom_tt_mo": {
     "median": 1,
     "values": [
      1
     ]
    },
    "housing_real_dd": {
     "median": 2.2,
     "values": [
      2.2
     ]
    },
    "tsy_12m": {
     "median": -12.3,
     "values": [
      -12.3
     ]
    },
    "tsy_24m": {
     "median": -19.1,
     "values": [
      -19.1
     ]
    },
    "unemp_rise_pp": {
     "median": 10.4,
     "values": [
      10.4
     ]
    }
   }
  }
 },
 "meta": {
  "equities": "OECD US share-price index, PRICE-ONLY, 1957+",
  "housing": "FHFA all-transactions HPI 1975+ (nominal & CPI-real); pre-1975 recessions have no housing row",
  "treasury": "10y total-return approximation from GS10",
  "classification": {
   "1957-09": "inflation_rates",
   "1960-05": "inflation_rates",
   "1970-01": "inflation_rates",
   "1973-12": "inflation_rates",
   "1980-02": "inflation_rates",
   "1981-08": "inflation_rates",
   "1990-08": "household_leverage",
   "2001-04": "valuation_corporate",
   "2008-01": "household_leverage",
   "2020-03": "exogenous"
  }
 }
} as const;
