// Plain-language definitions for every metric, written for a non-quant.
// Each: what it is, how it's computed, and how to read it. Used by <InfoTip/>.

export const GLOSSARY = {
  composite: {
    title: "Alpha Signal (shown 0–10)",
    what: "The headline score — a single, peer-relative read on how attractive a name's forward-looking setup is right now, relative to the rest of the universe.",
    calc: "A weighted blend of the five signal components (analyst revisions, catalysts, hype, positioning, cash runway), each first ranked against peers. Missing components are excluded, not counted as zero. Stored 0–100, displayed as x.x/10.",
    read: "5.0 = middle of the universe. 7.0+ = strong setup, near 10 = best-positioned name. It ranks opportunity within THIS universe — it is not a price target or an expected return, and in a sector-wide selloff someone is still 'top-ranked'.",
  },
  regime: {
    title: "Sector Regime",
    what: "A one-word read on whether the biotech tape is supportive (risk-on), hostile (risk-off), or in between (neutral).",
    calc: "Based on XBI (the sector's benchmark ETF): risk-on = 20-day return above +3% AND price above its 50-day average; risk-off = below −3% AND under the 50-day average; otherwise neutral.",
    read: "Same signal, different tape: pre-catalyst setups behave better in risk-on. In risk-off, expect stops to get hit more and size down. The %s next to XBI/ARKG/IBB are each fund's last-20-trading-day return; ▲/▼50dma = above/below its 50-day average price.",
  },
  relative_strength: {
    title: "vs XBI (relative strength)",
    what: "How much this stock has beaten or lagged the biotech sector itself over the last 20 trading days.",
    calc: "The name's 20-day return minus XBI's 20-day return. Not beta-adjusted — a high-volatility name will swing this more in both directions.",
    read: "+5% = outperformed the sector by 5 points; negative = lagging it. Use it to separate 'the name is strong' from 'everything is up'.",
  },
  ref_levels: {
    title: "Reference Levels (entry / stop / target)",
    what: "A pre-computed trade frame for the name — where you'd get in, where you'd admit you're wrong, and where you'd take profit — using the same math as the tracker's own logged calls.",
    calc: "Entry = last daily close. Stop = entry − 3× the stock's ATR (its average daily trading range over 14 days), so volatile names get wider stops. Target = entry + 3× the risk (entry-to-stop distance). Parameters were chosen from a 2-year backtest, net of trading costs.",
    read: "These are ORIENTATION, not a logged call — they're anchored on the last close and go stale the moment price gaps. The graded record lives in the Calls Log.",
  },
  liquidity_tier: {
    title: "Liquidity Tier (A / B / C)",
    what: "How much money the stock actually trades per day — i.e., how much size the desk can get in and out of without moving the price.",
    calc: "Median daily dollar volume over the last 20 sessions (median, so one blowout day can't flatter it). A = over $25M/day, B = $5–25M, C = under $5M.",
    read: "A = full clip sizes fine. B = watch sizing above ~$50k. C = thin float — expect slippage at any size; Tier C names never generate auto-calls.",
  },
  sentiment_7d: {
    title: "7-Day Social Sentiment",
    what: "The average tone of social-media chatter (Reddit / StockTwits / X) about this name over the past week.",
    calc: "Each captured post is scored from −1 (bearish) to +1 (bullish); this is the 7-day average across platforms.",
    read: "Above +0.3 = distinctly bullish chatter; near 0 = mixed/quiet; negative = bearish tone. Read it with the hype signal — tone AND volume together.",
  },
  signal_track_record: {
    title: "Signal Track Record",
    what: "This flag type's real, measured history: when this signal has fired in the past, what did the stock do next?",
    calc: "Every fire is graded from that day's close against the return 1 month later, minus XBI's return over the same window (so a sector rally doesn't flatter it). Hit rate = share of fires that beat the sector.",
    read: "This is the number that decides whether a signal earns trust. n < 10 = insufficient history — treat the flag as unproven, not bad. New signals run 'observe-only' until this record justifies letting them trigger calls.",
  },
  binary_event: {
    title: "Binary Event Risk",
    what: "A make-or-break event (trial results, FDA decision) where the stock can gap violently in either direction overnight.",
    calc: "Flagged when the next catalyst has impact ≥ 0.7. The ± expected move, when shown, comes from options pricing (volatility × time to event) — a rough, diffusive estimate that tends to UNDERSTATE the single-day jump.",
    read: "Desk default: exit before the event rather than hold through it. Auto-calls are built to time-stop the day before. If no options data exists, treat the potential gap as unbounded.",
  },
  catalyst_impact: {
    title: "Catalyst Impact (0–1)",
    what: "How market-moving this event is likely to be.",
    calc: "Default weights by event type (FDA decision 1.0, Phase 3 results 0.9, Phase 2 0.7, earnings 0.35, conferences ~0.3), manually overridable per event.",
    read: "≥ 0.7 is treated as a binary event: sell-before-the-event rules kick in and calls won't be generated too close to it.",
  },
  signal_decay: {
    title: "Signal Decay",
    what: "Whether the reason you're in the trade still exists: the name's Alpha Signal now vs. when the call was made.",
    calc: "Current composite minus the composite at call time (on the 0–100 internal scale).",
    read: "A large drop (−15+) means the setup that justified the call has faded — the tracker surfaces it as an early-exit consideration even if the stop hasn't been hit.",
  },
  win_rate: {
    title: "Win Rate",
    what: "The share of closed calls that made money.",
    calc: "Closed calls with a positive return ÷ all closed calls.",
    read: "Judge it WITH avg R, not alone: a 40% win rate is excellent if winners are +3R and losers −1R. High win rate + negative avg R = death by small cuts.",
  },
  avg_r: {
    title: "Average R",
    what: "The average result per call, measured in units of risk taken — the cleanest single measure of call quality.",
    calc: "Each call's profit ÷ its planned risk (entry-to-stop distance). Hitting the stop = −1R; hitting the target = +3R. Averaged across closed calls.",
    read: "Positive = the calls make more than they risk over time. +0.2R avg means every call earns ~20% of its risk on average — excellent if sustained.",
  },
  total_r: {
    title: "Total R",
    what: "Cumulative risk-units earned across all closed calls — the 'equity curve' number.",
    calc: "Sum of every closed call's R multiple.",
    read: "If you risked the same $ amount per call, this is proportional to total P&L. Rising over time = the system is adding value.",
  },
  equity_curve: {
    title: "Equity Curve (cumulative R)",
    what: "Running total of risk-units earned, plotted by exit date — the shape of the system's performance.",
    calc: "Each closed call adds its R (target hit ≈ +3, stopped ≈ −1, time-stop = whatever it was at exit) to the running sum.",
    read: "Up-and-to-the-right = working. Long flat/down stretches = the signals aren't paying in this tape. Read alongside the regime strip.",
  },
  rolling_perf: {
    title: "Rolling Win Rate & Avg R",
    what: "Call quality measured over just the most recent 20 closed calls — recent form, not lifetime average.",
    calc: "Trailing window of 20 closed calls, recomputed at every close.",
    read: "This is where improvement (or decay) shows first. Lifetime averages move slowly; the rolling line is the drift detector.",
  },
  cohorts: {
    title: "Cohorts (by month made)",
    what: "Calls grouped by the month they were GENERATED — the honest test of whether the learning loop is working.",
    calc: "Each cohort's calls were made under that month's signals and settings. If retuning from evidence works, later cohorts should grade better than earlier ones.",
    read: "Compare avg R across months, not within them. 'low n' cohorts are anecdotes — wait for n ≥ 10 before reading a trend.",
  },
  confidence: {
    title: "Confidence (0–100)",
    what: "How hard the book bets a trade — the conviction score that drives position size. Higher confidence = a bigger position.",
    calc: "Starts as the peer-relative setup quality (composite Alpha Signal), then is ADJUSTED by evidence: the signal's own graded track record bends it up if the signal has proven it pays (down if it hasn't), shrunk toward neutral when the record is thin; multiple distinct flags on one name nudge it up. With no track record yet, confidence ≈ the composite.",
    read: "This is deliberately evidence-weighted so 'bet big on conviction' can't become 'bet big on a guess'. As the learning loop grades signals, proven ones earn larger positions. 75+ = high conviction (top sizing), 60–75 = solid, below 60 = a smaller starter position.",
  },
  conviction_sizing: {
    title: "Position size (conviction-based)",
    what: "The share of the paper account put into each call — scaled by its confidence, not equal across trades.",
    calc: "size% = min% + (max% − min%) × (confidence/100)^concentration, convex so capital piles onto the very best setups. Then capped by liquidity tier (thin names get little or nothing), a portfolio gross-exposure limit (keeps dry powder), and a portfolio-heat limit (total risk if every stop hit at once). Tunable in config/calls.yaml.",
    read: "A concentrated book: the highest-confidence names get the biggest positions (up to the max %), low-confidence ones get starter sizes or are skipped. The row shows position % of the account and, on hover, the dollar cost and the risk-at-stop.",
  },
  postmortem: {
    title: "Post-mortem (\"why\")",
    what: "An automated attribution of why the call won or lost, computed from what price actually did — never hand-written.",
    calc: "Path analysis (did it ever work? did we round-trip a winner?), sector attribution (name move vs XBI over the trade), signal decay, catalyst discipline, and — 10 bars after exit — a hindsight verdict on the stop.",
    read: "'Never worked' blames the entry signal; 'peaked +2R then reversed' blames the exit rules; 'shakeout' (price snapped back after the stop) means the stop was too tight — each failure mode points at a different knob to fix.",
  },
  revision_velocity: {
    title: "Revision Velocity",
    what: "How fast — and which way — Wall Street analysts are changing their forecasts (EPS estimates and price targets).",
    calc: "Each recent revision is scored by direction (up = +, down = −) and weighted toward more recent ones, then ranked 0–100 vs. peers.",
    read: "High = analysts turning more bullish (a leading indicator that often precedes price). Low = estimates being cut.",
  },
  catalyst_score: {
    title: "Catalyst Score",
    what: "How much market-moving news is coming up soon for this name.",
    calc: "Sums upcoming catalysts (FDA decisions, trial readouts, earnings) weighted by their impact and how close they are — nearer events count more (time-decay) — then ranked 0–100.",
    read: "High = important, often binary events are imminent. That means bigger potential moves in both directions, so size positions with the event in mind.",
  },
  hype_divergence: {
    title: "Hype Divergence",
    what: "Whether social/retail chatter is building faster than the stock price has moved.",
    calc: "Z-score of the acceleration in mention volume (Reddit/StockTwits/X) minus the z-score of recent price change, ranked 0–100.",
    read: "High = buzz is ramping ahead of price (early-interest signal). Low = price moving with little chatter. The edge is chatter leading price.",
  },
  positioning: {
    title: "Positioning",
    what: "How crowded or squeezable the stock is, based on how heavily it's shorted (and options skew, when a feed provides it).",
    calc: "Short interest comes from FINRA's official bi-monthly publication, expressed as % of shares outstanding, then ranked as a percentile vs. the universe (0–100). Options skew joins the average when options data is available.",
    read: "High = heavily shorted / crowded — squeeze fuel, but also a caution sign that sophisticated money is betting against it. FINRA data updates twice a month, so this moves slowly by design.",
  },
  runway_penalty: {
    title: "Cash Runway",
    what: "A balance-sheet safety check for cash-burning biotechs.",
    calc: "From cash ÷ quarterly burn = quarters of runway. Shown 0–100: high = ample runway, low = approaching a cash cliff (dilution risk).",
    read: "Low values drag the Alpha Signal down. n/a = profitable or no meaningful burn (e.g., large pharma).",
  },
  tags: {
    title: "Subsector Tags",
    what: "Free-form theme labels you assign to each name (e.g. gene-editing, liquid-biopsy).",
    calc: "Editable per row or in watchlist.yaml; signal can be rolled up by theme in the Sector Heatmap.",
    read: "Use them to group names into the themes you actually trade.",
  },
  momentum: {
    title: "Momentum (Δ7d)",
    what: "The change in a name's (or theme's) Alpha Signal over the last ~7 days.",
    calc: "Latest composite minus the composite from ~7 days ago, using saved score history.",
    read: "Positive = the setup is improving (inflecting up); negative = deteriorating. The alpha is often in the change, not the level.",
  },
  raw: {
    title: "Raw",
    what: "The driver's actual measured value, in its own native units — before any scaling.",
    calc: "Pulled straight from the data: e.g. quarters of cash runway, a sum of weighted upcoming catalysts, the net direction of analyst revisions.",
    read: "Not comparable across rows — each driver is measured differently, so a raw 0.62 and a raw 7.8q live on totally different scales. It answers 'what is the underlying number?', not 'is it good?'.",
  },
  normalized: {
    title: "Normalized (0–100)",
    what: "The raw value re-expressed on a common 0–100, peer-relative scale where 50 = the universe average.",
    calc: "Cross-sectional ranking (z-score / percentile) of this name's raw value against all other names in the universe for that one driver.",
    read: "This is the equalizer that makes drivers comparable. 70+ = ranks well above peers on that driver; below 50 = below average. A 'good' raw number only becomes obvious here (e.g. 7.8q runway → ~97).",
  },
  weight: {
    title: "Weight",
    what: "How much this driver counts toward the final Alpha Signal — your priorities.",
    calc: "Set in scoring.yaml (editable, then POST /scores/reload). The active weights sum to 1.0; a missing component's weight is dropped from the denominator.",
    read: "Higher weight = this driver moves the score more. It reflects what you've decided matters, not anything about this particular stock.",
  },
  weighted: {
    title: "Weighted",
    what: "The points this driver actually contributes to the Alpha Signal.",
    calc: "Normalized × Weight. The Alpha Signal is the sum of these divided by the sum of the non-missing weights (a weighted average).",
    read: "This is where you see which drivers are carrying — or dragging — the score. Add the Weighted column (over the used weights) and you get the headline number.",
  },
  na: {
    title: "“n/a” vs 0",
    what: "n/a means there's no data for that input — deliberately different from a real 0.",
    calc: "Missing components are dropped from the Alpha Signal's weighting rather than counted as zero, so a name isn't penalized for patchy data.",
    read: "Common for thin-float names (options/short interest) and profitable names (runway). Treat low-confidence rows with extra caution.",
  },
};
